DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    job VARCHAR(50) NOT NULL,
    salary DOUBLE NOT NULL,
    bonus DOUBLE DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    phone VARCHAR(10) DEFAULT NULL
);